server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location /assets/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /predict {
        proxy_pass http://apartment-price-backend:8000/predict;
    }

    location /model {
        proxy_pass http://apartment-price-backend:8000/model;
    }

    location /schema {
        proxy_pass http://apartment-price-backend:8000/schema;
    }

    location /health {
        proxy_pass http://apartment-price-backend:8000/health;
    }
}