apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prediction-logs-pvc
  namespace: mlops-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apartment-price-backend
  namespace: mlops-demo
spec:
  replicas: 3
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: apartment-price-backend

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100

  template:
    metadata:
      labels:
        app: apartment-price-backend
    spec:
      containers:
        - name: backend
          image: apartment-price-backend:1.5
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_TRACKING_URI

            - name: DEFAULT_MODEL_URI
              value: "models:/apartment-price-regression@candidate"


            - name: OMP_NUM_THREADS
              value: "1"

            - name: OPENBLAS_NUM_THREADS
              value: "1"

            - name: MKL_NUM_THREADS
              value: "1"

            - name: NUMEXPR_NUM_THREADS
              value: "1"

            - name: VECLIB_MAXIMUM_THREADS
              value: "1"

            - name: PYTHONUNBUFFERED
              value: "1"

            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: AWS_SECRET_ACCESS_KEY

            - name: PREDICTION_LOG_PATH
              value: "/app/data/predictions/predictions_log.csv"

            - name: DRIFT_METRICS_PATH
              value: "/app/data/monitoring/latest_drift_metrics.json"

            - name: LOG_PREDICTIONS
              value: "true"

          volumeMounts:
            - name: prediction-logs
              mountPath: /app/data/predictions

            - name: drift-monitoring
              mountPath: /app/data/monitoring
              readOnly: true

      volumes:
        - name: prediction-logs
          persistentVolumeClaim:
            claimName: prediction-logs-pvc

        - name: drift-monitoring
          configMap:
            name: drift-metrics-runtime-config

---
apiVersion: v1
kind: Service
metadata:
  name: apartment-price-backend
  namespace: mlops-demo
spec:
  type: ClusterIP
  selector:
    app: apartment-price-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: apartment-price-backend-metrics
  namespace: mlops-demo
spec:
  type: NodePort
  selector:
    app: apartment-price-backend
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      nodePort: 30081
